'''Dictionnaire de test'''

patch_test = [{'source' : 'Kick in',    
                'reference' : 'SM91',
                'stand' : 'PP',
                'pad' : False,
                '48V' : False },
                {'source' : 'Kick Out',    
                'reference' : 'BETA52',
                'stand' : 'PP',
                'pad' : False,
                '48V' : False },
                {'source' : 'Snare Top',    
                'reference' : 'SM57',
                'stand' : 'PP',
                'pad' : False,
                '48V' : False },
                {'source' : 'Hit Hat',    
                'reference' : 'SM81',
                'stand' : 'PP',
                'pad' : True,
                '48V' : True },
                {'source' : ' Rack Tom',    
                'reference' : 'E604',
                'stand' : 'Clamp',
                'pad' : False,
                '48V' : False },
                {'source' : 'Floor Tom',    
                'reference' : 'MD421',
                'stand' : 'PP',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False },
                {'source' : '',    
                'reference' : '',
                'stand' : '',
                'pad' : False,
                '48V' : False }]

